// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc1F3P3fCfdHKkh3tuCcfNttGjOVUb2TY',
    appId: '1:63259313176:web:0788564b955c5e1ac0ef6d',
    messagingSenderId: '63259313176',
    projectId: 'newchatapp-7bff6',
    authDomain: 'newchatapp-7bff6.firebaseapp.com',
    storageBucket: 'newchatapp-7bff6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFp7YxxpYaI4mpk2OW9HN0anX2f7ww3kg',
    appId: '1:63259313176:android:10ce4add4cbf29c0c0ef6d',
    messagingSenderId: '63259313176',
    projectId: 'newchatapp-7bff6',
    storageBucket: 'newchatapp-7bff6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6rA7EE5V3Q_O-Twm57I8KZVJZx1MYogo',
    appId: '1:63259313176:ios:03d72bc9657e286cc0ef6d',
    messagingSenderId: '63259313176',
    projectId: 'newchatapp-7bff6',
    storageBucket: 'newchatapp-7bff6.appspot.com',
    iosClientId: '63259313176-uvqqj2fld6se1k873btvm7e4nukrj5tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPageAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6rA7EE5V3Q_O-Twm57I8KZVJZx1MYogo',
    appId: '1:63259313176:ios:517fe6183fe8fbe5c0ef6d',
    messagingSenderId: '63259313176',
    projectId: 'newchatapp-7bff6',
    storageBucket: 'newchatapp-7bff6.appspot.com',
    iosClientId: '63259313176-q8cnpsvktsu79bihkm6o5dioohieeadc.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPageAuth.RunnerTests',
  );
}
